# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20170329_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.IntegerField()),
                ('actor_type', models.CharField(choices=[('user', 'User')], max_length=30)),
                ('verb', models.CharField(choices=[('like', 'Like'), ('post', 'Post'), ('follow', 'Follow'), ('comment', 'Comment'), ('invite', 'Invite'), ('join', 'Join'), ('krak_write_access', 'Krak Write Access')], max_length=30)),
                ('object_id', models.IntegerField()),
                ('object_type', models.CharField(choices=[('post', 'Post'), ('krak', 'Krak'), ('user', 'User')], max_length=30)),
                ('target_id', models.IntegerField()),
                ('target_type', models.CharField(choices=[('user', 'User')], max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
