# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_notification'),
        ('social', '0003_profile_show_page_hints'),
    ]

    operations = [
    ]
