# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_merge_20170401_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='object_type',
            field=models.CharField(choices=[('post', 'Post'), ('krak', 'Krak'), ('comment', 'Comment'), ('user', 'User')], max_length=30),
        ),
    ]
