# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20170407_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='krak',
            name='author',
        ),
        migrations.RemoveField(
            model_name='krak',
            name='members',
        ),
        migrations.RemoveField(
            model_name='krakmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='krak',
        ),
        migrations.AlterField(
            model_name='like',
            name='item_type',
            field=models.CharField(choices=[('post', 'Post'), ('comment', 'Comment')], max_length=7),
        ),
        migrations.AlterField(
            model_name='notification',
            name='object_type',
            field=models.CharField(choices=[('post', 'Post'), ('comment', 'Comment')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('like', 'Like'), ('post', 'Post'), ('follow', 'Follow'), ('comment', 'Comment')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Krak',
        ),
        migrations.DeleteModel(
            name='KrakMember',
        ),
    ]
