# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20170419_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='show_page_hints',
        ),
    ]
